"""Add category to products

Revision ID: 55c619beb1a8
Revises: 99bb6ffe4ec2
Create Date: 2026-08-20 23:40:32.404610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c619beb1a8'
down_revision: Union[str, Sequence[str], None] = '99bb6ffe4ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.alter_column('products', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'discount',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
