"""add_role_to_users

Revision ID: 723db60027d7
Revises: 55c619beb1a8
Create Date: 2026-08-22 17:50:45.902539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723db60027d7'
down_revision: Union[str, Sequence[str], None] = '55c619beb1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'unpaid'::character varying"))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET role = 'SALES_MANAGER' WHERE role IS NULL")
    op.alter_column('users', 'role', nullable=False, server_default='SALES_MANAGER')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('invoices', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unpaid'::character varying"))
    # ### end Alembic commands ###
