"""add retail price and discount to products

Revision ID: 99bb6ffe4ec2
Revises: f344031be3b4
Create Date: 2026-08-20 09:54:33.011733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bb6ffe4ec2'
down_revision: Union[str, Sequence[str], None] = 'f344031be3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'products',
        sa.Column(
            'retail_price',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'products',
        sa.Column(
            'discount',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        )
    )

    op.alter_column(
        'products',
        'retail_price',
        server_default=None
    )

    op.alter_column(
        'products',
        'discount',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount')
    op.drop_column('products', 'retail_price')
    # ### end Alembic commands ###
